#abbreviations
abbrev-alias -g pss="sudo pacman -S"
abbrev-alias -g pns="sudo pacman --noconfirem -S"
abbrev-alias -g pns="sudo pacman --noconfirm -S"
abbrev-alias -g pn="sudo pacman --noconfirm"
abbrev-alias -g pr="sudo pacman -Rns"
abbrev-alias -g yn="yay --noconfirm"
abbrev-alias -g yns="yay --noconfirm -S"
abbrev-alias -g gg="| grep -i"
abbrev-alias -g cfv="vim ~/.vimrc"    
abbrev-alias -g cfz="vim ~/.zshrc"    
abbrev-alias -g sy="sudo systemctl"
abbrev-alias -g gt="gotop" 
abbrev-alias -g shc="ssh-connect"
abbrev-alias -g penv="python -m venv .venv" 
abbrev-alias -g aenv="source .venv/bin/activate" 
abbrev-alias -g mm="| most"
abbrev-alias -g v="vim"
abbrev-alias -g ss="sudo"
abbrev-alias -g md="mkdir -p"
abbrev-alias -g gc="git add -A && git commit -v&& git push"
#aliases
alias sl="colorls"
alias sll="colorls -l"
alias sla="colorls -lA"
alias ll="ls -l"
alias la="ls -lA"
alias ~="cd ~"
alias /="cd /"
alias 0="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias grep='grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
