#abbreviations
abbr -g pss="sudo pacman -S"
abbr -g pns="sudo pacman --noconfirm -S"
abbr -g pn="sudo pacman --noconfirm"
abbr -g pr="sudo pacman -Rns"
abbr -g yn="yay --noconfirm"
abbr -g yns="yay --noconfirm -S"
abbr -g gg="| grep -i"
abbr -g cfv="vim ~/.vimrc"    
abbr -g cfz="vim ~/.zshrc"    
abbr -g sy="sudo systemctl"
abbr -g penv="python -m venv .venv" 
abbr -g aenv="source .venv/bin/activate" 
abbr -g mm="| most"
abbr -g ll="| less"
abbr -g md="mkdir -p"
abbr -g gp="git add -A && git commit -v&& git push"
abbr -g gc="git clone"

#aliases
alias sl="colorls"
alias sll="colorls -l"
alias sla="colorls -A"
alias slla="colorls -lA"
alias ll="ls -l"
alias la="ls -lA"
alias ~="cd ~"
alias /="cd /"
alias 0="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ip="grc --colour=auto ip"
