#abbreviations
abbr -g pns="paru --noconfirm -S"
abbr -g pn="paru --noconfirm"
abbr -g pr="paru -Rns"
abbr -g gg="| grep -i"
abbr -g sy="sudo systemctl"
abbr -g penv="python -m venv .venv" 
abbr -g aenv="source .venv/bin/activate" 
abbr -g md="mkdir -p"
abbr -g gp="git add -A && git commit -v&& git push"
abbr -g gc="git clone"
abbr -g gs='git status'
abbr -g la='sla'
abbr -g sl="colorls"
abbr -g sll="colorls -l"
abbr -g sla="colorls -A"
abbr -g slla="colorls -lA"
abbr -g ll="ls -l"
abbr -g la="ls -lA"

#aliases
alias cat="bat"
alias ~="cd ~"
alias /="cd /"
alias 0="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ip="grc --colour=auto ip"
alias sudo="doas"
